---
- name: Update
  apt:
      update_cache: yes

- name: Install jdk
  apt:
    name : default-jdk 
    state : present

- name: Create dev group
  group:
    name: dev
    state: present    

- name: Create dev user
  user:
    name: dev
    state: present
    shell: /bin/bash    
    createhome: yes   
    home: /home/dev
    groups: dev

- name: Create qa group
  group:
    name: qa
    state: present      

- name: Create qa user
  user:
    name: qa
    state: present
    shell: /bin/bash    
    createhome: yes   
    home: /home/qa
    groups: qa
