---
- hosts: all
  become: true
  vars:
    default_container_name: final_project
    default_container_image: ubuntu
    ansible_python_interpreter : /usr/bin/python3

  tasks:
    - name: Install aptitude using apt
      apt: 
        name : aptitude 
        state : latest 
        update_cache : yes 
        force_apt_get : yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt: 
        update_cache : yes 
        name : docker-ce 
        state : latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: pull an image
      docker_image:
        name: nikita351/final_project:91
        source: pull
        state: present

    - name: Create and run container 
      docker_container:
        name: "{{ default_container_name }}"
        image: nikita351/final_project:91
        state: started
        auto_remove: true
        ports:
          - "8080:8080"
