---
- name: Install docker, pull and run image. After install java, create users and grops.
  hosts: PROD_SERVER
  become: true

  roles:
    - install_run_docker_container
    - install_java_create_users_and_groups